include: package:flutter_lints/flutter.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    avoid_print: false
    unnecessary_overrides: false # remove when mockito is fixed

    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_setters_without_getters: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    no_default_cases: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    unawaited_futures: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unsafe_html: true
    use_raw_strings: true
