name: Coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build Flutter image
        uses: docker/build-push-action@v6
        with:
          context: tool/ci
          load: true
          tags: lottie-flutter-ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test with coverage
        run: |
          docker run --rm -v "$PWD":/app -w /app lottie-flutter-ci \
            bash -c "flutter pub get && flutter test --coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
