name: Coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Coverage
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter test --coverage=coverage

      - name: Install coverage tools
        run: dart pub global activate coverage

      - name: format coverage
        run: $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
