name: Coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Flutter image
        run: docker build -t lottie-flutter-ci tool/ci
      - name: Test with coverage
        run: |
          docker run --rm -v "$PWD":/app -w /app lottie-flutter-ci \
            bash -c "flutter pub get && flutter test --coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
