name: Coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Coverage
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.1'
      - run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
